Access to OUD harm reduction supplies in Chicago

How are these materials dispersed through different neighborhoods in the city? In areas where supplies are available, how accessible are they? 

Lit review: 
- "Support for evidence-informed opioid policies and interventions: The role of racial attitudes, political affiliation, and opioid stigma" https://doi.org/10.1016/j.ypmed.2022.107034 
- "America’s opioid crisis: the need for an integrated public health approach" https://www.nature.com/articles/s41398-020-0847-1#Sec7 
- "Public Views About Opioid Overdose and People With Opioid Use Disorder" https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2844036 
- "Drug treatment perspectives and experiences among family and friends of people who use illicit opioids: A mixed methods study" https://doi.org/10.1016/j.josat.2023.209023

In [2]:
# Set up 

# Loading packages
import geopandas as gpd
import matplotlib.pyplot as plt
import networkx as nx
import osmnx as ox
import pandas as pd
import matplotlib.lines as mlines

from tqdm import tqdm
from shapely.geometry import Point, LineString, Polygon

# Importing data sets
chi_df = pd.read_csv("data/Chicago Health Atlas Data Download - Community areas.csv")

chi_gdf = gpd.read_file("data/Boundaries - Community Areas_20260520.zip")

amfardb_df = pd.read_csv("data/districtdata.csv")

In [7]:
chi_df.head()

,Layer,Name,GEOID,Population,Longitude,Latitude,HCSOP_2023-2024,HCSOPP_2023-2024,PCT-W_2020-2024,POP_2020-2024,VRDID_2020-2024,VRDIDR_2020-2024,VRDO_2020-2024,VRDOR_2020-2024,EMSOD_2023,MEOD_2023,MEODL_2023,MEODR_2023,CZD_2021-2025
0,NaN,NaN,NaN,NaN,NaN,NaN,"Prescription opiate misuse (count of adults), ...","Prescription opiate misuse rate (% of adults),...","Demographics, White (Non-Hispanic) (% of resid...","Population (residents), 2020-2024","Drug-induced mortality (count of deaths), 2020...","Drug-induced mortality rate (per 100,000 popul...","Drug overdose mortality (count of deaths), 202...","Drug overdose mortality rate (per 100,000 popu...",Opioid-related overdoses (count of EMS respons...,Opioid-related overdose mortality (count of de...,Opioid-related overdose mortality (Chicago loc...,Opioid-related overdose mortality rate (per 10...,"Drug abuse (crimes), 2021-2025"
1,Community area,Rogers Park,1.0,55454.0,-87.670171,42.009630,NaN,NaN,44.90256848483232,54023.51404694976,108.0,36.0,106.0,35.3,136.0,26.0,33.0,41.1,60.87564687319646
2,Community area,Norwood Park,10.0,41069.0,-87.803451,41.985248,NaN,NaN,71.70275824355703,42638.430864951515,32.0,16.2,30.0,15.3,18.0,2.0,3.0,4.7,9.017990589172369
3,Community area,Jefferson Park,11.0,26201.0,-87.771165,41.978836,NaN,NaN,55.98983052265246,26634.542326773037,24.0,18.2,24.0,18.2,23.0,6.0,7.0,23.4,13.38374547127953
4,Community area,Forest Glen,12.0,19579.0,-87.758358,41.993938,NaN,NaN,70.6717970991724,19886.375072714927,10.0,13.6,10.0,13.6,7.0,0.0,0.0,0.0,4.810867765903259

In [ ]:
chi_gdf.head()

,area_numbe,community,area_num_1,shape_area,shape_len,geometry
0,1.0,ROGERS PARK,1,5.125990e+07,34052.397576,"POLYGON ((-87.65456 41.99817, -87.65574 41.998..."
1,2.0,WEST RIDGE,2,9.842909e+07,43020.689458,"POLYGON ((-87.68465 42.01948, -87.68464 42.019..."
2,3.0,UPTOWN,3,6.509564e+07,46972.794555,"POLYGON ((-87.64102 41.9548, -87.644 41.95465,..."
3,4.0,LINCOLN SQUARE,4,7.135233e+07,36624.603085,"POLYGON ((-87.67441 41.9761, -87.6744 41.97602..."
4,5.0,NORTH CENTER,5,5.705417e+07,31391.669754,"POLYGON ((-87.67336 41.93234, -87.67342 41.932..."

Exploring drug and opioid use in Chicago

In [ ]:
# Drug use data

In [ ]:
# Drug use GDF

In [ ]:
# Visualizing

Exploring harm reduction resources

In [ ]:
# Types of resources 

## Safe injection/needle exchange

## Naloxone/Narcan - most widely available

## Test strips

In [ ]:
# Accessiblity of sites

In [ ]:
# Comparison to other healthcare facilities - hospitals and pharmacies

In [ ]:
# Mapping sites across the city

Access by neighborhood

In [ ]:
# Combining sites with community areas

In [ ]:
# Layering drug use and emergency data into mapped sites

In [ ]:
# Isochronal distance to difference resources 

## Safe injection/needle exchange

## Naloxone/Narcan

## Test strips

In [ ]:
# Identifying areas of need

Recommended interventions and legacy of discriminatory practices